### ISSUE TITLE
Check units for survey data

### ISSUE THREAD

**Issue by James-Thorson** [John-R-Wallace/JRWToolBox#1]
When I do:

```R
Data_Set <- JRWToolBox::WCGBTS_Combo_Catch_Wt(Species = "Ophiodon elongatus", YearRange = c(2003, 2015))
head(Data_Set)
```

... the first tow has a 19970.25 hectares, or almost 200 km^2.  Could you check the units?

**Comment by John-R-Wallace** [comment]
The Data Warehouse units on the file name was incorrect. 

They have corrected the units label.
