### ISSUE TITLE
missing function "chron"

### ISSUE THREAD

**Issue by taylori** [John-R-Wallace/JRWToolBox#2]
While trying to run code in https://github.com/James-Thorson/VAST/blob/master/examples/West_Coast_Annual_example_2017.R I got the following error caused by use of "chron" on Line 76 of [WCGBTS_Combo_Catch_Wt](https://github.com/John-R-Wallace/JRWToolBox/blob/master/R/WCGBTS_Combo_Catch_Wt.R#L76). 

```
Data_Set <- JRWToolBox::WCGBTS_Combo_Catch_Wt(Species = "Ophiodon elongatus", YearRange = c(2003, 2015))
Error in chron(format(as.POSIXlt(Out$Date, format = "%Y-%m-%dT%H:%M:%S"),  : 
  could not find function "chron"
```

I'm not sure where "chron" comes from but it doesn't seem to be in base R.

**Comment by John-R-Wallace** [comment]
WCGBTS_Combo_Catch_Wt(), via JRWToolBox::lib(), now checks for the chron package and installs it if needed.
