### ISSUE TITLE
Need for declaring repo

### ISSUE THREAD

**Issue by kellijohnson** [John-R-Wallace/JRWToolBox#3]
https://github.com/John-R-Wallace/JRWToolBox/blob/e5b1269ea01a543559426f3ac9b29496eee13683/R/WCGBTS_Combo_Catch_Wt.R#L6

Would it be possible to declare a repo in `JRWToolBox::lib` such that `update.packages(Package, ask = FALSE)` and all other package functions do not require the user to specify the repository. The popup window makes it difficult to run the code in a non-interactive session. The repo could be set at the beginning using 
```
       myrepo <- getOption("repos")
       myrepo["CRAN"] <- "https://ftp.osuosl.org/pub/cran"
       options(repos = myrepo)
       rm(myrepo)
```

**Comment by John-R-Wallace** [comment]
Added option to change repo to base CRAN, only if it's set to pop-up the repo menu.  Default is TRUE.
This avoids changing someones local repository, if it is already set.

if(autoAddRepo & options()$repos[names(options()$repos) %in% 'CRAN'] %in% "@CRAN@") 	 
       local({getOption("repos") -> r; r["CRAN"] <- "http://cran.fhcrc.org"; options(repos = r)})
