### ISSUE TITLE
WCBTS_Combo_Catch_Data required fields

### ISSUE THREAD

**Issue by CWetzel** [John-R-Wallace/JRWToolBox#4]
Additional fields are needed for calculation of compositional data and indices.  I suggest using this Var vector when pulling for the SP data frame:

Vars <- c("scientific_name", "year", "total_catch_wt_kg", "vessel", "tow", "cpue_kg_per_ha_der", "subsample_count", "subsample_wt_kg", "total_catch_numbers", "total_catch_wt_kg")

and using this Var vector when pulling the  All.Tows data frame:

Vars <- c("year", "vessel", "pass", "tow", "date_dim$full_date", "depth_m", "longitude_dd", "latitude_dd", "area_swept_ha_der", "trawl_id")

**Comment by John-R-Wallace** [comment]
Trawl_id, Subsample_count, Subsample_wt_kg, and Total_sp_numbers all added.

The user is left to calculate CPUE, e.g.:  CPUE_kg_per_ha = Total_sp_wt_kg/Area_Swept_ha
from the data given.
