### ISSUE TITLE
JW_Database_Bio_Code required fields

### ISSUE THREAD

**Issue by CWetzel** [John-R-Wallace/JRWToolBox#5]
I suggest changing the Var vector to include these variables:

Vars <- c("scientific_name", "year", "vessel", "pass", "tow", "date_dim$full_date", "depth_m", 
              "weight_kg", "length_cm", "sex", "age_years", "latitude_dd", "longitude_dd", 'trawl_id')

**Comment by John-R-Wallace** [comment]
Trawl_id added.
