### ISSUE TITLE
Add functionality to pull from multiple surveys

### ISSUE THREAD

**Issue by CWetzel** [John-R-Wallace/JRWToolBox#6]
Currently, the default URL only pulls from the NWFSC bottom trawl survey.  To improve the functionality of the code there needs to be an option to pull data from all surveys or from a specific survey (e.g., the triennial survey).

**Comment by John-R-Wallace** [comment]
Updated to retrieve all the surveys currently available.  AFSC slope still needs to added to the Data Warehouse.
